[package]
name = "dnlib"
version = "0.1.0"
authors = ["Philip Daniels <Philip.Daniels1971@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
walkdir = "2.2.7"
lazy_static = "1.3.0"
rayon = "1.0.3"
regex = "1"
unicase = "2.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_regex = "0.3.1"
strum = "0.15"
strum_macros = "0.15.0"

[dev-dependencies]
tempfile = "3.0"
