[package]
name = "dnlib"
version = "0.1.0"
authors = ["Philip Daniels <Philip.Daniels1971@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
walkdir = "2.2.7"

[dev-dependencies]
tempfile = "3.0"
